version: '3.8'
services:
  frontend:
    build:
      context: ./smart-vitals
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./smart-vitals:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - timescaledb
    environment:
      - DSN=${DSN}
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescaledb_data: